import { Document } from '../types';

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    name: 'Kitchen Floor Plan.pdf',
    type: 'pdf',
    size: '2.4 MB',
    uploadDate: '2025-03-01T10:30:00',
    status: 'completed',
    category: 'drawings',
    pages: 3,
    thumbnail: '/thumbnails/floor-plan.jpg',
  },
  {
    id: 'doc-2',
    name: 'Cabinet Specifications.pdf',
    type: 'pdf',
    size: '1.8 MB',
    uploadDate: '2025-03-01T10:35:00',
    status: 'completed',
    category: 'specifications',
    pages: 12,
  },
  {
    id: 'doc-3',
    name: 'Material Samples.jpg',
    type: 'image',
    size: '3.2 MB',
    uploadDate: '2025-03-01T11:15:00',
    status: 'completed',
    category: 'other',
    pages: 1,
  },
  {
    id: 'doc-4',
    name: 'Electrical Layout.dwg',
    type: 'cad',
    size: '1.5 MB',
    uploadDate: '2025-03-02T09:20:00',
    status: 'completed',
    category: 'drawings',
    pages: 1,
  },
  {
    id: 'doc-5',
    name: 'Supplier Catalog.pdf',
    type: 'pdf',
    size: '8.7 MB',
    uploadDate: '2025-03-02T14:45:00',
    status: 'processing',
    processingProgress: 65,
    category: 'other',
    pages: 48,
  },
  {
    id: 'doc-6',
    name: 'Client Requirements.xlsx',
    type: 'spreadsheet',
    size: '0.8 MB',
    uploadDate: '2025-03-03T08:30:00',
    status: 'error',
    errorMessage: 'Format not supported for automatic extraction',
    category: 'specifications',
    pages: 3,
  },
  {
    id: 'doc-7',
    name: 'Appliance Specifications.pdf',
    type: 'pdf',
    size: '4.2 MB',
    uploadDate: '2025-03-03T09:15:00',
    status: 'completed',
    category: 'specifications',
    pages: 24,
  },
  {
    id: 'doc-8',
    name: 'Countertop Details.pdf',
    type: 'pdf',
    size: '1.3 MB',
    uploadDate: '2025-03-03T10:45:00',
    status: 'completed',
    category: 'specifications',
    pages: 5,
  },
  {
    id: 'doc-9',
    name: 'Project Schedule.xlsx',
    type: 'spreadsheet',
    size: '0.5 MB',
    uploadDate: '2025-03-04T08:20:00',
    status: 'completed',
    category: 'schedules',
    pages: 2,
  },
  {
    id: 'doc-10',
    name: 'Kitchen Elevation.jpg',
    type: 'image',
    size: '2.1 MB',
    uploadDate: '2025-03-04T11:30:00',
    status: 'completed',
    category: 'drawings',
    pages: 1,
  },
];
